fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: check-ast
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: lint-python
        name: Lint Python
        entry: ruff check
        types: [python]
        language: system
        pass_filenames: false
